version: "3.8"
services:
  ibfflood:
    build:
      context: .
    image: ibf-stormsurge-pipeline
    ports:
      - "587:587"
    env_file:
      - secrets.env
    volumes: 
      - ./pipeline:/home/ibf
    command: run-stormsurge-model